server:
  port: 8761
spring:
  application:
    name: member
  redis:
        host: 192.168.18.129 #redis 服务器
  #      password:   #redis 密码
        port: 6379 #redis 端口
        lettuce:
          pool:
            max-idle: 30
            max-active: 30
            min-idle: 0
            max-wait: -1ms
   #数据库连接信息
  datasource:
        name: study-member
        url: jdbc:mysql://192.168.18.129:3306/study-member
        username: root
        password: 11100247
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
# 消息队列  # in-memory不适用内存代替 外部中间件（官方demo采用 memeroy 实现效果）
  activemq:
      broker-url: tcp://localhost:61616
      in-memory: false
      pool:
        enabled: true
        max-connections: 100
        idle-timeout: 5000
        expiry-timeout: 0
    #默认情况下activemq提供的是queue模式，若要使用topic模式需要配置下面配置
    #  spring.jms.pub-sub-domain=true
#    user:
#    password:
#配置 mq的节点

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka/

message:
       destionName: test
# 配置数据源
 # 运行时可以在控制台查看  启用和未启用的配置报告查看
debug: true